# Generated by Django 5.0.3 on 2024-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('joining_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('create_ts', models.DateTimeField()),
                ('mod_ts', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
